language: android
jdk: oraclejdk7
env: _JAVA_OPTIONS="-Xmx768m -Xms768m"
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    
    # The SDK version used to compile your project
    - android-19

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-19

# Emulator Management: Create, Start and Wait
before_script:
  - mkdir sdcard
  - mksdcard -l gnucash-sdcard 64M sdcard/gnucash-sdcard.img
  - echo no | android create avd --force -n test -t android-19 --abi x86 
  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim -gpu on -enable-kvm -sdcard sdcard/gnucash-sdcard.img &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &    