language: android
sudo: false
env: TARGET="android-21" NAME="android-21"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  
cache:
  directories:
   - $HOME/.android/avd/
   - $HOME/.gradle/caches/

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

    # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21


# Emulator Management: Create, Start and Wait
before_script:
  - chmod +x ./avd-test.sh
  - ./avd-test.sh
  #- mkdir sdcard
  #- mksdcard -l gnucash-sdcard 64M sdcard/gnucash-sdcard.img
  #- echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  #- emulator -avd test -no-skin -no-audio -no-boot-anim -no-window -sdcard sdcard/gnucash-sdcard.img &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &

script:
  - ./gradlew build cDDAT cPDAT

after_script:
  - cat ${TRAVIS_BUILD_DIR}/app/build/outputs/androidTest-results/connected/flavors/production/* # show logs
  - cat ${TRAVIS_BUILD_DIR}/app/build/outputs/androidTest-results/connected/flavors/development/* # show logs
